version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && chmod 777 /myapp/bin/rails && chmod 777 /myapp/bin/dev && /myapp/bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: docker
    depends_on:
      - db
